/**
 * Assessment Service
 * Business logic for assessment operations (PDF merge, compression, etc.)
 */

const formSubmissionRepository = require("../repositories/formSubmissionRepository");
const { AppError } = require("../middleware/errorHandler");
const axios = require("axios");
const { PDFDocument: PDFLibDocument, rgb } = require("pdf-lib");
const { cloudinary } = require("../config/cloudinary");
const fs = require("fs");
const path = require("path");
const archiver = require("archiver");

class AssessmentService {
  /**
   * Get submission by ID for assessment operations
   */
  async getSubmissionForAssessment(submissionId) {
    const submission = await formSubmissionRepository.findById(submissionId);
    if (!submission) {
      throw new AppError("Submission not found", 404);
    }
    return submission;
  }

  /**
   * Merge PDFs from submission
   */
  async mergePDFs(
    submissionId,
    documentIds,
    customerName,
    customerEmail,
    filename,
  ) {
    const submission = await this.getSubmissionForAssessment(submissionId);

    // Filter documents by selected IDs
    const selectedDocuments = submission.documents.filter((doc) =>
      documentIds.includes(doc._id.toString()),
    );

    if (selectedDocuments.length === 0) {
      throw new AppError("No documents selected", 400);
    }

    // Create a new PDF document using pdf-lib
    const mergedPdf = await PDFLibDocument.create();

    // Add cover page
    const coverPage = mergedPdf.addPage([595, 842]);
    const { width, height } = coverPage.getSize();

    coverPage.drawText("Documents Assessment", {
      x: 50,
      y: height - 100,
      size: 24,
      color: rgb(0, 0, 0),
    });

    coverPage.drawText(`Customer: ${customerName}`, {
      x: 50,
      y: height - 150,
      size: 14,
      color: rgb(0, 0, 0),
    });

    coverPage.drawText(`Email: ${customerEmail}`, {
      x: 50,
      y: height - 170,
      size: 14,
      color: rgb(0, 0, 0),
    });

    coverPage.drawText(`Date: ${new Date().toLocaleDateString()}`, {
      x: 50,
      y: height - 190,
      size: 14,
      color: rgb(0, 0, 0),
    });

    // Process each document
    for (let i = 0; i < selectedDocuments.length; i++) {
      const document = selectedDocuments[i];
      await this.embedDocument(mergedPdf, document, i);
    }

    // Add footer to last page
    const pages = mergedPdf.getPages();
    if (pages.length > 0) {
      const lastPage = pages[pages.length - 1];
      const { width, height } = lastPage.getSize();

      lastPage.drawText("Generated by Wise Steps Consultant", {
        x: 50,
        y: 50,
        size: 10,
        color: rgb(0.5, 0.5, 0.5),
      });

      lastPage.drawText(`Generated on: ${new Date().toISOString()}`, {
        x: 50,
        y: 30,
        size: 8,
        color: rgb(0.5, 0.5, 0.5),
      });
    }

    // Save merged PDF
    const safeFilename = (
      filename ||
      customerName ||
      "merged_documents"
    ).replace(/[^a-zA-Z0-9_-]/g, "_");
    const fileName = `${safeFilename}_${Date.now()}.pdf`;
    const filePath = path.join(__dirname, "../uploads", fileName);

    const mergedPdfBytes = await mergedPdf.save();
    fs.writeFileSync(filePath, mergedPdfBytes);

    return { filePath, fileName };
  }

  /**
   * Embed document into PDF
   */
  async embedDocument(mergedPdf, document, index) {
    try {
      if (!document.cloudinaryUrl) {
        this.createPlaceholderPage(
          mergedPdf,
          document,
          index,
          "Document not available",
        );
        return;
      }

      let fetchUrl = document.cloudinaryUrl;
      if (
        document.cloudinaryPublicId &&
        document.mimetype.startsWith("image/")
      ) {
        const format = document.mimetype === "image/png" ? "png" : "jpg";
        fetchUrl = cloudinary.url(document.cloudinaryPublicId, {
          resource_type: "image",
          type: "upload",
          format,
          quality: "auto",
          secure: true,
        });
      }

      const response = await axios.get(fetchUrl, {
        responseType: "arraybuffer",
        headers: {
          Accept: document.mimetype.startsWith("image/")
            ? document.mimetype
            : "*/*",
        },
      });

      if (document.mimetype === "application/pdf") {
        const pdfBytes = response.data;
        const pdfDoc = await PDFLibDocument.load(pdfBytes);
        const pages = await mergedPdf.copyPages(
          pdfDoc,
          pdfDoc.getPageIndices(),
        );

        pages.forEach((page) => {
          mergedPdf.addPage(page);
        });
      } else if (document.mimetype.startsWith("image/")) {
        const contentType =
          response.headers?.["content-type"] || document.mimetype;
        await this.embedImage(
          mergedPdf,
          document,
          response.data,
          index,
          contentType,
        );
      } else {
        this.createPlaceholderPage(mergedPdf, document, index);
      }
    } catch (error) {
      console.error(
        `Error embedding document ${document.originalname}:`,
        error,
      );
      this.createPlaceholderPage(
        mergedPdf,
        document,
        index,
        "Error embedding document",
      );
    }
  }

  /**
   * Embed image into PDF
   */
  async embedImage(mergedPdf, document, imageBytes, index, contentType) {
    const imagePage = mergedPdf.addPage([595, 842]);
    const { width, height } = imagePage.getSize();

    let image;
    const normalizedType = (
      contentType ||
      document.mimetype ||
      ""
    ).toLowerCase();

    if (normalizedType.includes("jpeg") || normalizedType.includes("jpg")) {
      image = await mergedPdf.embedJpg(imageBytes);
    } else if (normalizedType.includes("png")) {
      image = await mergedPdf.embedPng(imageBytes);
    } else {
      // Fallback: if Cloudinary returns an unexpected image format, try PNG embedding
      image = await mergedPdf.embedPng(imageBytes);
    }

    const imgDims = image.scale(1);
    const scale = Math.min(
      (width - 100) / imgDims.width,
      (height - 150) / imgDims.height,
    );
    const scaledWidth = imgDims.width * scale;
    const scaledHeight = imgDims.height * scale;
    const x = (width - scaledWidth) / 2;
    const y = height - 100 - scaledHeight;

    imagePage.drawText(`Document ${index + 1}: ${document.fieldName}`, {
      x: 50,
      y: height - 50,
      size: 16,
      color: rgb(0, 0, 0),
    });

    imagePage.drawText(`File: ${document.originalname}`, {
      x: 50,
      y: height - 70,
      size: 12,
      color: rgb(0.5, 0.5, 0.5),
    });

    imagePage.drawImage(image, {
      x: x,
      y: y,
      width: scaledWidth,
      height: scaledHeight,
    });
  }

  /**
   * Create placeholder page
   */
  createPlaceholderPage(mergedPdf, document, index, errorMessage = null) {
    const placeholderPage = mergedPdf.addPage([595, 842]);
    const { width, height } = placeholderPage.getSize();

    placeholderPage.drawText(`Document ${index + 1}: ${document.fieldName}`, {
      x: 50,
      y: height - 100,
      size: 16,
      color: rgb(0, 0, 0),
    });

    placeholderPage.drawText(`File: ${document.originalname}`, {
      x: 50,
      y: height - 130,
      size: 14,
      color: rgb(0, 0, 0),
    });

    if (errorMessage) {
      placeholderPage.drawText(errorMessage, {
        x: 50,
        y: height - 160,
        size: 12,
        color: rgb(0.8, 0.2, 0.2),
      });
    } else {
      placeholderPage.drawText(`Type: ${document.mimetype}`, {
        x: 50,
        y: height - 150,
        size: 14,
        color: rgb(0, 0, 0),
      });

      placeholderPage.drawText(
        `Size: ${(document.size / 1024 / 1024).toFixed(2)} MB`,
        {
          x: 50,
          y: height - 170,
          size: 14,
          color: rgb(0, 0, 0),
        },
      );
    }
  }

  /**
   * Compress PDFs
   */
  async getCompressionDownloadUrl(document) {
    if (!document.cloudinaryUrl) return null;

    if (document.cloudinaryPublicId && document.mimetype.startsWith("image/")) {
      const format = document.mimetype === "image/png" ? "png" : "jpg";
      return cloudinary.url(document.cloudinaryPublicId, {
        resource_type: "image",
        type: "upload",
        format,
        quality: "auto",
        secure: true,
      });
    }

    return document.cloudinaryUrl;
  }

  async downloadDocumentBytes(document) {
    const url = await this.getCompressionDownloadUrl(document);
    if (!url) {
      throw new Error("Document download URL is unavailable");
    }

    const response = await axios.get(url, {
      responseType: "arraybuffer",
      headers: {
        Accept: document.mimetype.startsWith("image/")
          ? document.mimetype
          : "*/*",
      },
    });

    return Buffer.from(response.data);
  }

  async convertImageToPdfBytes(document, imageBuffer) {
    const imagePdf = await PDFLibDocument.create();
    await this.embedImage(
      imagePdf,
      document,
      imageBuffer,
      0,
      document.mimetype,
    );
    return await imagePdf.save({ useObjectStreams: false, compress: false });
  }

  async createErrorPdfBytes(document, message) {
    const errorPdf = await PDFLibDocument.create();
    const page = errorPdf.addPage([595, 842]);
    page.drawText(`Failed to include ${document.originalname}`, {
      x: 50,
      y: 760,
      size: 16,
      color: rgb(0.8, 0.1, 0.1),
    });
    page.drawText(message, {
      x: 50,
      y: 730,
      size: 12,
      color: rgb(0.2, 0.2, 0.2),
      maxWidth: 500,
    });
    return await errorPdf.save({ useObjectStreams: false, compress: false });
  }

  async compressPdfBytes(pdfBytes, compressionLevel) {
    try {
      const pdfDoc = await PDFLibDocument.load(pdfBytes);

      let quality;
      switch (compressionLevel) {
        case "low":
          quality = 0.8;
          break;
        case "medium":
          quality = 0.6;
          break;
        case "high":
          quality = 0.4;
          break;
        case "5mb":
          quality = 0.35;
          break;
        default:
          quality = 0.6;
      }

      return await pdfDoc.save({
        useObjectStreams: false,
        compress: true,
        imageQuality: quality,
        removeMetadata: true,
      });
    } catch (error) {
      console.error("PDF compression failed, returning original bytes:", error);
      return pdfBytes;
    }
  }

  async compressPDFs(
    submissionId,
    documentIds,
    compressionLevel,
    customerName,
  ) {
    if (
      !submissionId ||
      !documentIds ||
      !Array.isArray(documentIds) ||
      documentIds.length === 0
    ) {
      throw new AppError("Submission ID and document IDs are required", 400);
    }

    const submission = await this.getSubmissionForAssessment(submissionId);

    const documentsToCompress = submission.documents.filter(
      (doc) =>
        documentIds.includes(doc._id.toString()) &&
        doc.cloudinaryUrl &&
        (doc.mimetype === "application/pdf" ||
          doc.mimetype.startsWith("image/")),
    );

    if (documentsToCompress.length === 0) {
      throw new AppError("No valid documents found to compress", 400);
    }

    const tempDir = path.join(__dirname, "../uploads", `temp_${Date.now()}`);
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    const compressedFiles = [];

    for (const doc of documentsToCompress) {
      let fileBytes;
      let outputBytes;
      let finalFilename;

      try {
        fileBytes = await this.downloadDocumentBytes(doc);

        if (doc.mimetype.startsWith("image/")) {
          outputBytes = await this.convertImageToPdfBytes(doc, fileBytes);
          const baseName = doc.originalname.replace(/\.[^/.]+$/, "");
          finalFilename = `compressed_${baseName}.pdf`;
        } else {
          outputBytes = await this.compressPdfBytes(
            fileBytes,
            compressionLevel,
          );
          finalFilename = `compressed_${doc.originalname}`;
        }
      } catch (error) {
        console.error(`Error processing document ${doc.originalname}:`, error);
        const baseName = doc.originalname.replace(/\.[^/.]+$/, "");

        if (!fileBytes) {
          outputBytes = await this.createErrorPdfBytes(
            doc,
            `Unable to download or read the document for compression. ${error.message}`,
          );
          finalFilename = `failed_${baseName}.pdf`;
        } else {
          outputBytes = fileBytes;
          finalFilename = `original_${doc.originalname}`;
        }
      }

      const compressedPath = path.join(tempDir, finalFilename);
      fs.writeFileSync(compressedPath, outputBytes);

      compressedFiles.push({
        path: compressedPath,
        filename: finalFilename,
      });
    }

    if (compressedFiles.length === 0) {
      fs.rmSync(tempDir, { recursive: true, force: true });
      throw new AppError("Failed to compress any documents", 500);
    }

    // Create ZIP file
    const zipPath = path.join(
      tempDir,
      `${customerName || "compressed"}_pdfs.zip`,
    );
    await this.createZipFile(compressedFiles, zipPath);

    return {
      zipPath,
      zipFileName: `${customerName || "compressed"}_pdfs.zip`,
      tempDir,
    };
  }

  /**
   * Create ZIP file
   */
  async createZipFile(files, zipPath) {
    return new Promise((resolve, reject) => {
      const output = fs.createWriteStream(zipPath);
      const archive = archiver("zip", { zlib: { level: 9 } });

      output.on("close", resolve);
      archive.on("error", reject);

      archive.pipe(output);
      files.forEach((file) => {
        archive.file(file.path, { name: file.filename });
      });
      archive.finalize();
    });
  }
}

module.exports = new AssessmentService();
